### PR TITLE
Updated to version 1.2.0

### PR DESCRIPTION
**Pull request by eggzilla**

### CODE REVIEW

**Comment by eggzilla** [comment]
This does not seem like a package error. Closing and reopoening for a new test.

```
  File "/opt/conda/lib/python3.5/site-packages/binstar_client/__init__.py", line 200, in _check_response
    raise ErrCls(msg, res.status_code)
binstar_client.errors.ServerError: ('Bad Gateway: Invalid responses from another server/proxy. ([GET] https://api.anaconda.org/channels/conda-forge/main -> 502)', 502)
```

**Comment by jakirkham** [comment]
Please fork and submit changes from branches on your fork in the future.

Also please [re-render](https://github.com/conda-forge/conda-smithy#re-rendering-an-existing-feedstock) with `conda-smithy` version `1.3.3` and bump the build number. The reason for the build number bump is to handle a Travis CI compatibility issue.

**Comment by eggzilla** [comment]
Apologies, still learning the process. I will perform the re-rendering and build bump in a fork right away.

**Comment by jakirkham** [comment]
No worries. Thanks for doing that.

**Comment by eggzilla** [comment]
Sure :-)

**Pull request merged**
