### PR TITLE
Updated to stack version 1.6.1

### PR DESCRIPTION
**Pull request by eggzilla**

### CODE REVIEW

**Comment by bgruening** [comment]
@isuruf

Have you see this before?
```
No BINSTAR_TOKEN present, so no upload is taking place. The distribution just built is not already available for conda-forge.
```
Linux was updated, OSX not?
https://anaconda.org/conda-forge/stack/files

**Comment by isuruf** [comment]
That was the PR build. master build is still in the queue.

**Comment by bgruening** [comment]
Meh, the travis-ci logo tricked me on the readme. Sorry for the noise!

**Comment by eggzilla** [comment]
Me too, thanks for asking!

**Pull request merged**
