### PR TITLE
Windows build of stack 2.3.1

### PR DESCRIPTION
**Pull request by LaurentRDC**
Hello,

stack 2.3.1 is not available for Windows, for some reason. This PR re-builds the recipe.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by LaurentRDC** [comment]
@conda-forge-admin, please rerender

**Comment by LaurentRDC** [comment]
@conda-forge/stack Can someone merge this so `stack` can be used to build Haskell programs from source in conda-forge itself? e.g. https://github.com/conda-forge/pandoc-plot-feedstock/pull/20

**Comment by LaurentRDC** [comment]
@conda-forge/core 

Hello, this feedstock appears abandoned. 

However, `stack` is also an important part of the Haskell toolchain, which is required to build Haskell packages from source (e.g. conda-forge/pandoc-plot-feedstock/pull/20 or conda-forge/pandoc-feedstock/pull/70). Would it be possible to add me to the maintainers so I can keep this running?

**Comment by isuruf** [comment]
Sure, please add yourself as a maintainer in `recipe/meta.yaml` in this PR.

**Comment by LaurentRDC** [comment]
Triggering CI again

**Comment by LaurentRDC** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
