### PR TITLE
Fix tests to exit in case of error, add linux run dependencies and setup

### PR DESCRIPTION
**Pull request by dbast**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

The double ampersand is not properly executed during tests (yaml to test.sh casting issue?) and thus exit codes unequal to zero are lost. Which means the tests are succeeding even though there was an error.

This PR just shows the problem, the solution is either adding the correct `run` dependencies to the recipe or other steps so that stack finds what it needs (configuration or ENV variables?).

### CODE REVIEW

**Comment by LaurentRDC** [comment]
Hi Daniel,

Thank you for your report!

I think the best thing to do in this case is to write a test script. See [here for the documentation](https://conda-forge.org/docs/maintainer/adding_pkgs.html#built-in-tests). Relevant quote:

> Alternatively, you can add a file called `run_test.py` in the recipe that will be run at test time. This allows an arbitrarily complicated test script.

If you are up for it, you can write that test yourself. Otherwise, let me know and I can take care of it.

**Comment by LaurentRDC** [comment]
It appears that GHC 8.8.4 is not available on CentOS 6, which is the default for conda-forge builds.

You can force the conda-forge build to use CentOS 7 by [following the instructions here](https://conda-forge.org/docs/maintainer/knowledge_base.html#using-centos-7).

**Comment by dbast** [comment]
@LaurentRDC I was thinking the same first, but it seems CentOS 7 is already used, see https://github.com/conda-forge/stack-feedstock/blob/master/.ci_support/linux_64_.yaml

Other reports indicate that the error message is misleading and this could be a missing lib, e.g. https://github.com/commercialhaskell/stack/issues/4144 -> That would mean we need to add `ncurses  # [linux]` to run dependencies.

**Comment by dbast** [comment]
Linux error:
```
+ stack setup
~/feedstock_root/build_artifacts/stack_1604416701420/test_tmp/helloworld ~/feedstock_root/build_artifacts/stack_1604416701420/test_tmp
No setup information found for ghc-8.8.4 on your platform.
This probably means a GHC bindist has not yet been added for OS key 'linux64-gmp4'.
```

Pinging also @notestaff who does great work for https://github.com/conda-forge/git-annex-feedstock which uses stack/ghc. Any idea here?

**Comment by dbast** [comment]
Still fails on linux after adding ncurses.

Do we need to setup something in "${STACK_ROOT}/config.yaml" so that stack finds ncurses and other libs on linux... (like it is done in https://github.com/conda-forge/git-annex-feedstock/blob/master/recipe/build_nodepFalse.sh)?

**Comment by dbast** [comment]
Is it worth setting up the right `config.yaml` in run_tests.sh before `stack setup` .... or any other things to try? This could then serve other feedstock as an example on howto use stack.

**Comment by dbast** [comment]
Do those lines list all the required libs: https://github.com/commercialhaskell/stack/blob/v2.5.1/src/Stack/Setup.hs#L957 ?

**Comment by dbast** [comment]
libtinfo is part of the ncurses conda package ... 

hm, why does setup still not work on linux?

Any ideas to try?

**Comment by dbast** [comment]
yay. green! Maybe that can be cleaned up a bit.

**Comment by LaurentRDC** [comment]
I'm happy to see that your work paid off!

**Comment by dbast** [comment]
Ok. Squashed everything into 3 clear commits:
* moving to test scripts that properly exit on error
* Switching to CentOS 7 image for linux
* adding run requirements for linux + linux setup so that the libs are found

So this is ready to merge from my side... it shows how users of the feedstock need to setup stack to build their feedstock.

Future work could:
* Unify mac and linux setup code
* Provide compiler activation scripts, that contain all the setup code, so the users don't need to do it on their own before calling stack (as we also now do it in the run_test.sh).

**Comment by LaurentRDC** [comment]
Great, thank you for your contribution

**Pull request merged**
